use sales_data;


SELECT 
CUSTOMERNAME,
RECENCY,
FREQUENCY,
MONETARY,
SEGMENTED_RECENCY,
SEGMENTED_FREQUENCY,
SEGMENTED_MONETARY,
SEGMENTED_FM,
CASE
	WHEN SEGMENTED_FM = 5 AND SEGMENTED_RECENCY IN (1,2) THEN "Can\'t Lose Them"
    WHEN SEGMENTED_FM IN (5,4) AND SEGMENTED_RECENCY IN (3,4) THEN 'Loyal Customers'
    WHEN SEGMENTED_FM IN (5,4) AND SEGMENTED_RECENCY = 5 THEN 'Champions'
    WHEN SEGMENTED_FM IN (4,3) AND SEGMENTED_RECENCY IN (1,2) THEN 'At Risk'
    WHEN SEGMENTED_FM = 3 AND SEGMENTED_RECENCY = 3 THEN 'About to Sleep'
	WHEN SEGMENTED_FM IN (3,2) AND SEGMENTED_RECENCY IN (4,5) THEN 'Potential Loyalist'
	WHEN SEGMENTED_FM IN (2,1) AND SEGMENTED_RECENCY In (2,1) THEN 'Hibernating' 
    WHEN SEGMENTED_FM IN (2,1) AND SEGMENTED_RECENCY = 3 THEN 'Needs Attention' 
    WHEN SEGMENTED_FM = 1 AND SEGMENTED_RECENCY = 4 THEN 'Promising'
    WHEN SEGMENTED_FM = 1 AND SEGMENTED_RECENCY = 5 THEN 'New Customers'
END AS RFM_SEG
FROM Customer_v2;
