use sales_data;

SET @LASTDATE = (SELECT ADDDATE(MAX(ORDERDATE),2) FROM sales_data);

SELECT 
rfm.CUSTOMERNAME,
RECENCY,
FREQUENCY,
MONETARY,
NTILE(4) OVER (ORDER BY rfm.RECENCY) AS SEGMENTED_RECENCY,
NTILE(4) OVER (ORDER BY rfm.FREQUENCY) AS SEGMENTED_FREQUENCY,
NTILE(4) OVER (ORDER BY MONETARY) AS SEGMENTED_MONETARY
FROM (SELECT 
CUSTOMERNAME,
DATEDIFF(@LASTDATE, MAX(ORDERDATE)) AS RECENCY,
COUNT(ORDERNUMBER) AS FREQUENCY,
SUM(SALES) AS MONETARY
FROM sales_data
GROUP BY CUSTOMERNAME) rfm;
